### ISSUE TITLE
bsg-target.cmake is missing!

### ISSUE THREAD

**Issue by DinkoAtanasov** [leenderthayen/BSG#9]
On a fresh install, it seems this file _bsg-targets.cmake_ is missing. 
The output below is from the configuration of CRADLE that is using the _find_package(BSG REQUIRED)_

```
[cmake] CMake Error at /usr/local/lib/bsg/bsg-config.cmake:6 (include):
[cmake]   include could not find load file:
[cmake] 
[cmake]     //lib/bsg/bsg-targets.cmake
[cmake] Call Stack (most recent call first):
[cmake]   source/CMakeLists.txt:21 (find_package)
[cmake] 
[cmake] 
[cmake] Configuring incomplete, errors occurred!
```

**Comment by leenderthayen** [comment]
Hi Dinko,

Can you give a little more info into the steps you did? Are you using the master branch or dev branch, for both BSG and CRADLE? Both are undergoing a lot of development, but I thought the master branches of both should be compatible. If not, I'll take a quick look and it should be an easy fix. Note that the master branch of CRADLE doesn't actually support BSG (at least in a proper way) and there was no way I could quickly put them together reliably, hence the heavy dev work in those branches.

Cheers,
Leendert

**Comment by DinkoAtanasov** [comment]
Hi Leendert, 
Thanks for the quick reply. I used the master branches for both. Let me know if I should change to the development branch of CRADLE. 

I saw that BSG is actually properly installing the files into "/usr/local". 
Here the output of the make install process
```
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/lib/bsg-targets.cmake
-- Installing: /usr/local/lib/bsg-targets-noconfig.cmake
-- Installing: /usr/local/lib/bsg-config.cmake
-- Up-to-date: /usr/local/lib/bsg-config-version.cmake
```
I have no clue what could be the problem as this ${_prefix} should be the default (/usr/local), which is empty in the CRADLE's cmake process. 

Best, 
Dinko

**Comment by leenderthayen** [comment]
Hi Dinko,

I might need some more information to figure this out. I just tried a fresh install of the master branch and this worked with no obvious problems. Maybe there's a file permission error hiding underneath? Does the executable in the build directory work fine? If it does you can always just run it from there, e.g., by adding the build directory to your path in your .bashrc. Otherwise you can try changing the install prefix either manually or just using the ccmake gui.

You could switch to the dev branch, but it's relying on some libraries I wrote which I think are still in private repo's. Also some of the paths in cmake are still hardcoded to my personal environment so you'd have to go and muck about in it. While this might be an unsatisfactory answer right now, if you can wait until September when I plan to finish the work I'd suggest trying to use the master branch results for now.

Cheers,
Leendert

**Comment by DinkoAtanasov** [comment]
Yes, the executable works just fine and it is also installed correctly. What I meant is that when you configure with CMake CRADLE (master branch), there is an error, pointing to this "bsg-targets.cmake" file as it is not being found. The installed directory is "**/usr/local/lib/bsg-targets.cmake**", but in CRADLE I get "**//lib/bsg-targets.cmake**". You see the file path in one case is "/usr/local" and in the other just "/", so it seems that something is missing or is not being picked and as this file does not bother the execution of the program you see it only when you try to use it as an external library. Hope it is clear now. 

If you are working on the code now and finding these bugs I can wait couple of weeks to make the final simulations.

**Comment by leenderthayen** [comment]
Hi Dinko,

Sorry I didn't catch that initially. There's probably something wrong in the config files which are written when the BSG library is compiled. Since also those things are being streamlined in the dev branch, I'm not keen on mucking about right now in the master branch of BSG in case something else breaks for someone else.

I'll be working in September on the code again to prepare for the MORA workshop where I'm supposed to present these things, but I'm positively swamped right now with too many other projects.

**Comment by DinkoAtanasov** [comment]
Hi Leendert, 
I found the problem. It was a residual directory from previous BSG installation, called "/usr/local/lib/bsg". It had a "bsg-config.cmake" on its own that was picked by CMake, but pointing to a wrong location. After removing it, CRADLE complained it did not find the BSG program, however, it allowed me this time to set BSG_DIR to the right location, fixing the cmake and executable build. So next time I will be more careful and try to find all BSG folder and clean them before installing anything else. 

Best, 
Dinko
